### ISSUE TITLE
Markdown Files Not Being Outputted

### ISSUE THREAD

**Issue by DuroCodes** [neplextech/typedoc-nextra#1]
This package looks very promising, but I can't seem to get it to work.

I have the following code for `docgen.mjs`, but the markdown files don't seem to be created.

```mjs
import { createDocumentation } from 'typedoc-nextra';

await createDocumentation({
  jsonInputPath: `${process.cwd()}/out.json`,
  tsconfigPath: `${process.cwd()}/../../packages/handler/tsconfig-base.json`,
  output: `${process.cwd()}/pages/docs`,
  markdown: true,
});
```

Also, I had another issue whenever I try to do `typedoc` with `npx`/`pnpx`. It would say `error Invalid structure in plugin typedoc-nextra, no load function found.`

**Comment by twlite** [comment]
Hello, could I get more info? Maybe the project repository would be helpful if possible.

If you are on a monorepo, you can set `input` property to the location where `typedoc.json` is located at. If you are not on a monorepo project or you want to document single project, you can specify `input` property to point your main file of that project.

Example:

#### Monorepo

`typedoc.json`

```jsonc
{
    "$schema": "https://typedoc.org/schema.json",
    "entryPointStrategy": "packages", // represents monorepo
    "entryPoints": [ // list of your packages under the monorepo to generate docs for
        "packages/package-a",
        "packages/package-b"
    ],
    ...
}
```

`docgen.mjs`

```mjs
import { createDocumentation } from 'typedoc-nextra';

await createDocumentation({
    input: './path/to/root',
    output: './path/to/output',
    markdown: true,
    print: true // use this if you want it to display docs on console as well
});
```

#### Other

`docgen.mjs`

```mjs
import { createDocumentation } from 'typedoc-nextra';

await createDocumentation({
    input: './path/to/package/src/index.ts',
    output: './path/to/output',
    tsconfigPath: './path/to/tsconfig',
    markdown: true,
    print: true // use this if you want it to display docs on console as well
});
```

**Comment by DuroCodes** [comment]
Here's the [monorepo](https://github.com/durocodes/spark). I haven't commited the new changes with the plugin, yet.

I have the `docgen.mjs` inside of `apps/docs/src/utils`, I'll try using just `input` instead of `jsonInputPath`, thanks for such a quick response!

**Comment by DuroCodes** [comment]
I figured out what the issue was, tysm!

```js
import { createDocumentation } from 'typedoc-nextra';

await createDocumentation({
  input: `${process.cwd()}/../../packages/handler/src/index.ts`,
  output: `${process.cwd()}/src/pages/docs`, // I had this set to the wrong directory on accident 😅
  tsconfigPath: `${process.cwd()}/../../packages/handler/tsconfig-base.json`,
  markdown: true,
  print: true,
});
```
